// codegen.cpp
#include "codegen.h"
#include <fstream>
#include <iostream>

CodeGenerator::CodeGenerator(const std::string& outputFile)
    : outputFile(outputFile), labelCounter(0) {}

std::string CodeGenerator::newLabel() {
    return "L" + std::to_string(++labelCounter);
}

void CodeGenerator::emit(const std::string& line) {
    outputLines.push_back(line);
}

void CodeGenerator::addError(const std::string& msg) {
    errors.push_back("Code generation error: " + msg);
}

void CodeGenerator::generate(const ProgramNode& ast) {
    emit("; Generated by Pascal Compiler");
    emit("; Target: Virtual Machine / P-code");
    emit("");

    emit(".data");
    emit("");
    emit(".code");
    emit("_start:");

    // Генерируем основной блок
    if (ast.block) {
        if (auto block = dynamic_cast<BlockNode*>(ast.block.get())) {
            generateBlock(*block);
        }
    }

    emit("    HALT");
}

void CodeGenerator::generateBlock(const BlockNode& node) {
    for (const auto& stmt : node.statements) {
        generateStatement(stmt.get());
    }
}

void CodeGenerator::generateStatement(const ASTNode* node) {
    if (auto assign = dynamic_cast<const AssignmentNode*>(node)) {
        generateAssignment(assign);
    }
    else if (auto ifNode = dynamic_cast<const IfNode*>(node)) {
        generateIf(ifNode);
    }
    else if (auto readNode = dynamic_cast<const ReadNode*>(node)) {
        generateRead(readNode);
    }
    else if (auto writeNode = dynamic_cast<const WriteNode*>(node)) {
        generateWrite(writeNode);
    }
    else if (auto block = dynamic_cast<const BlockNode*>(node)) {
        generateBlock(*block);
    }
}

void CodeGenerator::generateAssignment(const AssignmentNode* node) {
    generateExpression(node->expression.get());
    emit("    STORE " + node->name);
}

void CodeGenerator::generateIf(const IfNode* node) {
    std::string elseLabel = newLabel();
    std::string endLabel = newLabel();

    generateExpression(node->condition.get());
    emit("    JZ " + elseLabel);

    generateStatement(node->thenBranch.get());
    emit("    JMP " + endLabel);

    emit(elseLabel + ":");
    if (node->elseBranch) {
        generateStatement(node->elseBranch.get());
    }

    emit(endLabel + ":");
}

void CodeGenerator::generateRead(const ReadNode* node) {
    for (const auto& var : node->variables) {
        emit("    READ " + var);
    }
}

void CodeGenerator::generateWrite(const WriteNode* node) {
    for (const auto& expr : node->expressions) {
        generateExpression(expr.get());
        emit("    WRITE");
    }
}

void CodeGenerator::generateExpression(const ASTNode* node) {
    if (auto num = dynamic_cast<const NumberNode*>(node)) {
        emit("    PUSH " + std::to_string(num->value));
    }
    else if (auto ident = dynamic_cast<const IdentifierNode*>(node)) {
        emit("    LOAD " + ident->name);
    }
    else if (auto binOp = dynamic_cast<const BinaryOpNode*>(node)) {
        generateExpression(binOp->left.get());
        generateExpression(binOp->right.get());

        if (binOp->op == "+") emit("    ADD");
        else if (binOp->op == "-") emit("    SUB");
        else if (binOp->op == "*") emit("    MUL");
        else if (binOp->op == "/") emit("    DIV");
    }
    else if (auto unOp = dynamic_cast<const UnaryOpNode*>(node)) {
        generateExpression(unOp->operand.get());
        if (unOp->op == "-") emit("    NEG");
    }
    else if (auto call = dynamic_cast<const FuncCallNode*>(node)) {
        generateFuncCall(call);
    }
}

void CodeGenerator::generateFuncCall(const FuncCallNode* node) {
    for (const auto& arg : node->arguments) {
        generateExpression(arg.get());
    }
    emit("    CALL " + node->name);
}

void CodeGenerator::writeOutput() {
    std::ofstream file(outputFile);
    if (!file.is_open()) {
        addError("Cannot open output file: " + outputFile);
        return;
    }

    for (const auto& line : outputLines) {
        file << line << std::endl;
    }

    std::cout << "Generated code written to " << outputFile << std::endl;
}