; Generated by Pascal Compiler
; Target: Virtual Machine / P-code

.data

.code
_start:
    PUSH 5
    STORE x
    PUSH 10
    STORE y
    LOAD x
    LOAD y
    JZ L1
    LOAD x
    LOAD y
    ADD
    STORE result
    JMP L2
L1:
    LOAD y
    LOAD x
    SUB
    STORE result
L2:
    LOAD result
    WRITE
    HALT
